### ISSUE TITLE
KeyError when using examples/main_step_1_direct.py

### ISSUE THREAD

**Issue by lucasasmith** [canva-public/dbt-column-lineage-extractor#3]
I'm encountering a `KeyError` when testing with the `main_step_1_direct.py` script and adding one model to the `li_selected_model` list. I believe this is because the code below is looking for an all lowercase model name ([as set here](https://github.com/canva-public/dbt-column-lineage-extractor/blob/3acb2ca794a09d35bf065c33bec253a7ec14e737/py_package/dbt_column_lineage_extractor/extractor.py#L156)), but my model test isn't all lowercase to begin with. Could be wrong but may help in tracking down the issue.

https://github.com/canva-public/dbt-column-lineage-extractor/blob/3acb2ca794a09d35bf065c33bec253a7ec14e737/py_package/dbt_column_lineage_extractor/extractor.py#L164

Error output with specifics removed:
```
  File "/folder/.venv/lib/python3.12/site-packages/dbt_column_lineage_extractor/extractor.py", line 164, in get_columns_lineage_from_sqlglot_lineage_map
    columns_lineage[model_node][column] = []
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'model.Project_Name.model__name_here'
```

Setting the variable:
```python
# Add the models you want to extract lineage for, or leave it empty to extract lineage for all models
li_selected_model = ["model.Project_Name.model__name_here"]
```

**Comment by wenwu35** [comment]
Thanks @lucasasmith  for raising this! You are right, it was the lower case issue.
It's now been fixed in https://github.com/canva-public/dbt-column-lineage-extractor/pull/4
