### ISSUE TITLE
It seems that `compiled_code` is not always available

### ISSUE THREAD

**Issue by wilsonkong-canva** [canva-public/dbt-column-lineage-extractor#7]
Traceback (most recent call last):
  File "/Users/wilsonk/anaconda3/envs/analytics/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-17-eb4834769a83>", line 1, in <module>
    lineage_map = extractor.build_lineage_map()
  File "/Users/wilsonk/anaconda3/envs/analytics/lib/python3.10/site-packages/dbt_column_lineage_extractor/extractor.py", line 127, in build_lineage_map
    model_sql = model_info["compiled_code"]
KeyError: 'compiled_code'

**Comment by wenwu35** [comment]
Hey @wilsonkong-canva, just to confirm if the `manifest.json` was generated by `dbt docs generate` and not overwritten afterwards by another dbt command (e.g., `dbt ls`)? According to [dbt docs](https://docs.getdbt.com/reference/commands/cmd-docs), `dbt docs generate` will:


> Compiling the resources in your project, so that their compiled_code will be included in [manifest.json](https://docs.getdbt.com/reference/artifacts/manifest-json).

**Comment by wilsonkong-canva** [comment]
right! that could be the case. `docs generate` takes a long time for our `transform` project. and I did work on something else in between.

Let me give a small scope docs generate a go. 

On the other hand, is that possible for the tool to identify that `compiled_code` is not in, let's `docs generate` for the `node` that's being requested?

**Comment by wenwu35** [comment]
> On the other hand, is that possible for the tool to identify that `compiled_code` is not in, let's `docs generate` for the `node` that's being requested?

Yes, that's a good idea. I'll add it when I get a chance.

**Comment by wilsonkong-canva** [comment]
redo `dbt docs generate` solved the issue.
